DROP DATABASE IF EXISTS CDAC;
CREATE DATABASE CDAC;
USE CDAC;
CREATE TABLE students(
    sid INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(30),
    Marks INT
);

CREATE TABLE courses(
    cid INT PRIMARY KEY AUTO_INCREMENT,
    course_name VARCHAR(20),
    Fees DECIMAL(9,2)
);